### ISSUE TITLE
SQLAlchemy ignores existing database and creates new instead

### ISSUE THREAD

**Issue by xbound** [karec/cookiecutter-flask-restful#11]
Hi, I've been using your great template (slightly tweaked to meet my needs) in one of my flask apps and noticed odd problem.
After changing SQLALCHEMY_DATABASE_URI to `sqlite:///myapi.db`  and initializing sqlite database using `flask` cli commands: `init` -> `migrate` -> `upgrade`. I get an error when querying `User` table in python shell:
```shell
$ flask shell
>>>  from myapi.models.user import User
>>> User.query.all()
Traceback (most recent call last):
  File "/home/linux-hp/git-clones/restful_api/.venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/home/linux-hp/git-clones/restful_api/.venv/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: user

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/linux-hp/git-clones/restful_api/.venv/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2843, in all
    return list(self)
  File "/home/linux-hp/git-clones/restful_api/.venv/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2995, in __iter__
    return self._execute_and_instances(context)
  File "/home/linux-hp/git-clones/restful_api/.venv/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 3018, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/home/linux-hp/git-clones/restful_api/.venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/home/linux-hp/git-clones/restful_api/.venv/lib/python3.5/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/linux-hp/git-clones/restful_api/.venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/home/linux-hp/git-clones/restful_api/.venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/home/linux-hp/git-clones/restful_api/.venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/home/linux-hp/git-clones/restful_api/.venv/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/linux-hp/git-clones/restful_api/.venv/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 248, in reraise
    raise value.with_traceback(tb)
  File "/home/linux-hp/git-clones/restful_api/.venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/home/linux-hp/git-clones/restful_api/.venv/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: user [SQL: 'SELECT user.id AS user_id, user.username AS user_username, user.email AS user_email, user.password AS user_password, user.active AS user_active \nFROM user'] (Background on this error at: http://sqlalche.me/e/e3q8)
```
As far as I understood from googling that this somewhat related to Python import system, but I can't currently come up with any  solution except of workaround with storing sqlite database in `/tmp/` directory. How this problem can be solved?

**Comment by karec** [comment]
Hi,

This error is telling you that the database does not has a table named user, could you drop the content of the migration generated by `flask db migrate` ?

**Comment by xbound** [comment]
That's what `migrate` command outputs:
```

**Comment by karec** [comment]
Just to be sure, can you try to use an absolute path for your `SQLALCHEMY_DATABASE_URI` instead of a relative one ? Looks like when you start your shell it doesn't pick to correct path and use an empty database

**Comment by xbound** [comment]
It works with absolute path, but I'm more interested on how to make it works with relative one. If I would like clone my repo on another machine I would need manually change path to sqlite development database which is not very convenient.

**Comment by karec** [comment]
Yes I understand, the simplest way is to do this is to update the `config.py` file with something like this:

```python
import os

DB_PATH = os.path.join(os.path.dirname(__file__), 'my_db.db')
SQLALCHEMY_DATABASE_URI = "sqlite:////{}".format(DB_PATH)
```

You can off course update the DB_PATH to fit your needs, but this way `DB_PATH` will always be an absolute path, but based on the location of your config file (inside app directory)

This is one of the solution and maybe the simplest, but you can also hook inside the `create_app` function to dynamically get a path relative to your application instance and update your config accordingly during this step

**Comment by xbound** [comment]
That worked for me. I've also tried this approach in similar app that uses [dynaconf extension](https://dynaconf.readthedocs.io/en/latest/guides/configuration.html) to load configuration variables from .yaml file instead of python config file , but, unfortunately, it failed with the same error. Still, thanks anyway.

**Comment by karec** [comment]
For this kind of tool you can try to hook in the app factory, for example in this template something like this should work (not tested)

```python
def configure_app(app, testing=False):
    """set configuration for application
    """
    # default configuration
    app.config.from_object('myapi.config')

    if testing is True:
        # override with testing config
        app.config.from_object('myapi.configtest')
    else:
        # override with env variable, fail silently if not set
        app.config.from_envvar("MYAPI_CONFIG", silent=True)

    # override SQLALCHEMY_DATABASE_URI
    path = os.path.join(os.path.dirname(__file__), my_settings.get('DB_PATH'))
    # or using app.root_path
    # path = os.path.join(app.root_path, my_settings.get('DB_PATH'))

    app.config['SQLALCHEMY_DATABASE_URI'] = "sqlite://{}".format(path)
```

**Comment by karec** [comment]
closing, don't hesitate to re-open this issue if needed
