### ISSUE TITLE
module 'myapi.manage' has no attribute 'cli'

### ISSUE THREAD

**Issue by sgubianpm** [karec/cookiecutter-flask-restful#54]
Hi @karec !

It seems that the latest changes (regarding cli from flask) gives an error after the ```pip install -e .```, I just run ```flask --help``` to check and I get this (I tried with python 3.8 and 3.9, same issue):

```bash
Traceback (most recent call last):
  File "/Users/johndoe/Software/python-virtualenvs/TestRestful/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2455, in resolve
    return functools.reduce(getattr, self.attrs, module)
AttributeError: module 'myapi.manage' has no attribute 'cli'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/johndoe/Software/python-virtualenvs/TestRestful/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/Users/johndoe/Software/python-virtualenvs/TestRestful/lib/python3.9/site-packages/flask/cli.py", line 994, in main
    cli.main(args=sys.argv[1:])
  File "/Users/johndoe/Software/python-virtualenvs/TestRestful/lib/python3.9/site-packages/flask/cli.py", line 600, in main
    return super().main(*args, **kwargs)
  File "/Users/johndoe/Software/python-virtualenvs/TestRestful/lib/python3.9/site-packages/click/core.py", line 1052, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "/Users/johndoe/Software/python-virtualenvs/TestRestful/lib/python3.9/site-packages/click/core.py", line 914, in make_context
    self.parse_args(ctx, args)
  File "/Users/johndoe/Software/python-virtualenvs/TestRestful/lib/python3.9/site-packages/click/core.py", line 1615, in parse_args
    rest = super().parse_args(ctx, args)
  File "/Users/johndoe/Software/python-virtualenvs/TestRestful/lib/python3.9/site-packages/click/core.py", line 1370, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/Users/johndoe/Software/python-virtualenvs/TestRestful/lib/python3.9/site-packages/click/core.py", line 2347, in handle_parse_result
    value = self.process_value(ctx, value)
  File "/Users/johndoe/Software/python-virtualenvs/TestRestful/lib/python3.9/site-packages/click/core.py", line 2309, in process_value
    value = self.callback(ctx, self, value)
  File "/Users/johndoe/Software/python-virtualenvs/TestRestful/lib/python3.9/site-packages/click/core.py", line 1270, in show_help
    echo(ctx.get_help(), color=ctx.color)
  File "/Users/johndoe/Software/python-virtualenvs/TestRestful/lib/python3.9/site-packages/click/core.py", line 693, in get_help
    return self.command.get_help(self)
  File "/Users/johndoe/Software/python-virtualenvs/TestRestful/lib/python3.9/site-packages/click/core.py", line 1295, in get_help
    self.format_help(ctx, formatter)
  File "/Users/johndoe/Software/python-virtualenvs/TestRestful/lib/python3.9/site-packages/click/core.py", line 1326, in format_help
    self.format_options(ctx, formatter)
  File "/Users/johndoe/Software/python-virtualenvs/TestRestful/lib/python3.9/site-packages/click/core.py", line 1524, in format_options
    self.format_commands(ctx, formatter)
  File "/Users/johndoe/Software/python-virtualenvs/TestRestful/lib/python3.9/site-packages/click/core.py", line 1587, in format_commands
    for subcommand in self.list_commands(ctx):
  File "/Users/johndoe/Software/python-virtualenvs/TestRestful/lib/python3.9/site-packages/flask/cli.py", line 561, in list_commands
    self._load_plugin_commands()
  File "/Users/johndoe/Software/python-virtualenvs/TestRestful/lib/python3.9/site-packages/flask/cli.py", line 539, in _load_plugin_commands
    self.add_command(ep.load(), ep.name)
  File "/Users/johndoe/Software/python-virtualenvs/TestRestful/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2447, in load
    return self.resolve()
  File "/Users/johndoe/Software/python-virtualenvs/TestRestful/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2457, in resolve
    raise ImportError(str(exc)) from exc
ImportError: module 'myapi.manage' has no attribute 'cli'
```

Any idea?
Thanks a lot!
Best regards,

Sylvain

**Comment by tedghose** [comment]
in setup.py change cli to init

**Comment by pompierninja** [comment]
then run

`pip install -e . `

**Comment by karec** [comment]
Fixed in main branch and removed all `myapi <commands>` calls to fit Flask default CLI (README has been updated accordingly)
